### PR TITLE
Add option to display the sidebar on the right side.

### PR DESCRIPTION
**Pull request by ElAberino**
In my project i wanted to have the sidebar on the right side and I thought it might be a good feature for the theme. I placed the option under `Open sidebar` in `Theme Config`, because it appears to me that the `Sidebar Configuration` is for things that are within the sidebar.

### CODE REVIEW

**Comment by ElAberino** [comment]
@pmoreno-rodriguez Thanks for reviewing my changes and your feedback :)

I added the missing transition. Do you see any other issues?

**Comment by pmoreno-rodriguez** [comment]
Hi @ElAberino, I've been reviewing your changes and they work fine, but there's still something wrong. In mobile mode the menu icon overlaps the social media icons, as you can see in the screenshot. You need to create some additional css class so that these icons appear on the left when the menu icon is on the right. To do this you need to include some if else statements in the code.
On the other hand, in the blueprints.yaml file, you enter the text directly, without doing the corresponding translation in the languages.yaml file. I suggest you follow the translation pattern that already exists in the theme to be able to make it extensible to other languages.

Thank you very much for your collaboration. I will take a look at the modifications that you send me.

captura_editorial_theme

**Comment by pmoreno-rodriguez** [comment]
Hello again. a hint for the social icons code. In base.html.twig (in Theme Options section):
```
{% set sidebar_position = theme_config.sidebar_position|defined('left') %}
....
<body class="is-preload {{ page.header.body_classes }} sidebar-{{ sidebar_position }}">
```
In the social.html.twig file, you could use something like this:

```
{% set sidebar_style = sidebar_position == 'right' ? 'right: unset; left: -0.5em;' : '' %}

<ul class="icons" style="{{ sidebar_style }}">

....rest of code ....
```

**Comment by ElAberino** [comment]
@pmoreno-rodriguez Your suggestions worked prefectly fine:
image

I added the translations, too.

**Comment by pmoreno-rodriguez** [comment]
Hi @ElAberino , 
I've been testing your latest changes further, and I'm suggesting a few more:
1) Since there is no CSS class for the left sidebar position, it might be more appropriate to create a toggle variable right_sidebar in the theme blueprint, since what the code does is add the class sidebar-right in case the sidebar is positioned on the right, otherwise there is no additional class.
2) I've also made a minor change to social.html.twig so that only if the sidebar is set to the right will `style` appear in the HTML code.

I'll try to change the pull request to approve it if you're okay with my changes.

**Comment by ElAberino** [comment]
Hi @pmoreno-rodriguez ,

that totally makes sense and im absolutely okay with it.

**Pull request merged**
